name: Build image

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: OpenAlcoholics/github-action-helm@v0.3.0
        with:
          subcommand: lint
          path: .
          namespace: blindfoldedsurgery
      - uses: OpenAlcoholics/github-action-helm@v0.3.0
        with:
          subcommand: lint
          path: .
          namespace: blindfoldedsurgery
          strict: true

  template:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: OpenAlcoholics/github-action-helm@v0.3.0
        with:
          raw_command: template . --debug
