name: Build and deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: OpenAlcoholics/github-action-helm@v0.3.0
        with:
          subcommand: lint
          path: .
          namespace: blindfoldedsurgery
      - uses: OpenAlcoholics/github-action-helm@v0.3.0
        with:
          subcommand: lint
          path: .
          namespace: blindfoldedsurgery
          strict: true

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: install helm chart
        uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          subcommand: upgrade
          release_name: website
          ref: .
          namespace: blindfoldedsurgery
          install: true
          atomic: true
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}